set -g mouse on

set -g set-clipboard on
setw -g mode-keys vi
# set -g default-terminal "xterm-256color"
# set-option -ga terminal-overrides ",xterm-256color:Tc"
set-option -g default-terminal "screen-256color"
set-option -g default-shell /bin/zsh

source-file ~/.tmux/iceberg.tmux.conf

# # allow for navigating between words with option
set-window-option -g xterm-keys on

# # Allow the arrow key to be used immediately after changing windows
set-option -g repeat-time 1

# # Set window notifications
set -g monitor-activity on
set -g visual-activity on

# # Scrollback buffer
set -g history-limit 10000

# # Update files on focus (using for neovim)
set -g focus-events on

# # Status update interval
set -g status-interval 1

# # Reduce time to wait for Escape key. You'll want this for neovim.
set-option escape-time 40

# setw -g mode-keys vi
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-prefix-highlight'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'jatap/tmux-base16-statusline'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'catppuccin/tmux'

set -g @yank_selection_mouse 'clipboard'
set -g @yank_with_mouse on
set -g @shell_mode 'vi'

set -g @catppuccin_flavour 'mocha' # or frappe, macchiato, mocha

run '~/.tmux/plugins/tpm/tpm'

bind C-l send-keys 'C-l'

bind P send-keys -X copy-pipe-and-cancel "xsel -i --clipboard; tmux paste-buffer"
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -se c -i'
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel 'xclip -se c -i'

is_vim="ps -o state= -o comm= -t '#{pane_tty}' | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|n?vim?x?)(diff)?$'"

bind-key -n 'C-h' if-shell "$is_vim" 'send-keys C-h' { if -F '#{pane_at_left}' '' 'select-pane -L' }
bind-key -n 'C-j' if-shell "$is_vim" 'send-keys C-j' { if -F '#{pane_at_bottom}' '' 'select-pane -D' }
bind-key -n 'C-k' if-shell "$is_vim" 'send-keys C-k' { if -F '#{pane_at_top}' '' 'select-pane -U' }
bind-key -n 'C-l' if-shell "$is_vim" 'send-keys C-l' { if -F '#{pane_at_right}' '' 'select-pane -R' }

bind-key -T copy-mode-vi 'C-h' if -F '#{pane_at_left}' '' 'select-pane -L'
bind-key -T copy-mode-vi 'C-j' if -F '#{pane_at_bottom}' '' 'select-pane -D'
bind-key -T copy-mode-vi 'C-k' if -F '#{pane_at_top}' '' 'select-pane -U'
bind-key -T copy-mode-vi 'C-l' if -F '#{pane_at_right}' '' 'select-pane -R'
